name: Build and Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.toolchain || 'default' }} (${{ matrix.build_type }}, ${{ matrix.asio }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        build_type: [static, shared]
        asio: [with_asio, no_asio]
        toolchain: [msvc, mingw]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Only needed for MSVC
      - name: Setup MSBuild (MSVC)
        if: matrix.os == 'windows-latest' && matrix.toolchain == 'msvc'
        uses: microsoft/setup-msbuild@v1

      - name: Configure (MSVC)
        if: matrix.os == 'windows-latest' && matrix.toolchain == 'msvc'
        shell: cmd
        run: |
          cmake -B build -G "Ninja" ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DBUILD_SHARED_LIBS=$([[ "${{ matrix.build_type }}" == "shared" ]] && echo ON || echo OFF) ^
            -DNO_ASIO_BUILD=$([[ "${{ matrix.asio }}" == "no_asio" ]] && echo ON || echo OFF)

      - name: Configure (Unix / MinGW)
        if: matrix.os != 'windows-latest' || matrix.toolchain == 'mingw'
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" && "${{ matrix.toolchain }}" == "mingw" ]]; then
            cmake -B build -G "Ninja" -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
              -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_SHARED_LIBS=${{ matrix.build_type == 'shared' && 'ON' || 'OFF' }} \
              -DNO_ASIO_BUILD=${{ matrix.asio == 'no_asio' && 'ON' || 'OFF' }}
          else
            cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_SHARED_LIBS=${{ matrix.build_type == 'shared' && 'ON' || 'OFF' }} \
              -DNO_ASIO_BUILD=${{ matrix.asio == 'no_asio' && 'ON' || 'OFF' }}
          fi

      - name: Build (MSVC)
        if: matrix.os == 'windows-latest' && matrix.toolchain == 'msvc'
        shell: cmd
        run: cmake --build build

      - name: Build (Unix / MinGW)
        if: matrix.os != 'windows-latest' || matrix.toolchain == 'mingw'
        shell: bash
        run: cmake --build build

      - name: Package
        shell: bash
        run: |
          pkg_dir="package/${{ matrix.os }}-${{ matrix.toolchain || 'default' }}"
          mkdir -p "$pkg_dir"/{lib,include}

          if [[ "${{ matrix.os }}" == "windows-latest" && "${{ matrix.toolchain }}" == "msvc" ]]; then
            find build -type f \( -name "*.lib" -o -name "*.dll" \) -exec cp {} "$pkg_dir/lib/" \;
          elif [[ "${{ matrix.os }}" == "windows-latest" && "${{ matrix.toolchain }}" == "mingw" ]]; then
            find build -type f \( -name "*.a" -o -name "*.dll" \) -exec cp {} "$pkg_dir/lib/" \;
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            find build -type f \( -name "*.a" -o -name "*.so" \) -exec cp {} "$pkg_dir/lib/" \;
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            find build -type f \( -name "*.a" -o -name "*.dylib" \) -exec cp {} "$pkg_dir/lib/" \;
          fi

          cp GekkoLib/include/gekkonet.h "$pkg_dir/include/" || true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.toolchain || 'default' }}-${{ matrix.build_type }}-${{ matrix.asio }}
          path: package/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate release tag
        run: echo "TAG=v$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create packages
        shell: bash
        run: |
          for platform_dir in artifacts/*; do
            pkg_name=$(basename "$platform_dir")
            mkdir -p "GekkoNet-$pkg_name"
            cp -r "$platform_dir/"* "GekkoNet-$pkg_name/" || true
            if [ "$(find "GekkoNet-$pkg_name" -type f | wc -l)" -gt 0 ]; then
              tar -czf "GekkoNet-$pkg_name-Release.tar.gz" -C "GekkoNet-$pkg_name" .
            fi
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: GekkoNet-*-Release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: Documentation
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Build docs
        run: |
          cmake -B build -DBUILD_DOCS=ON
          cmake --build build --target docs

      - name: Upload docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/GekkoLib/docs/html
          
      - name: Deploy
        uses: actions/deploy-pages@v4
